# Generated by Django 4.2.3 on 2025-11-25 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="child",
            name="name",
            field=models.CharField(max_length=100, verbose_name="სახელი და გვარი"),
        ),
        migrations.AlterField(
            model_name="child",
            name="parent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="user.parent",
                verbose_name="მშობელი",
            ),
        ),
    ]
