# Generated by Django 4.2.3 on 2025-12-14 16:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_child_name_alter_child_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="child",
            name="otp_code",
        ),
        migrations.RemoveField(
            model_name="child",
            name="otp_expiry",
        ),
        migrations.RemoveField(
            model_name="parent",
            name="password",
        ),
        migrations.AddField(
            model_name="child",
            name="access_code",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="parent",
            name="otp_code",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name="parent",
            name="otp_expiry",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
