# Generated by Django 4.2.3 on 2025-12-16 18:44

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_remove_child_otp_code_remove_child_otp_expiry_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Logo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="ლოგოს სახელი")),
                (
                    "image",
                    models.ImageField(upload_to="logos/", verbose_name="ლოგოს სურათი"),
                ),
            ],
            options={
                "verbose_name": "ლოგო",
                "verbose_name_plural": "ლოგოები",
            },
        ),
        migrations.AddField(
            model_name="child",
            name="created",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="შეიქმნა"
            ),
        ),
        migrations.AddField(
            model_name="child",
            name="date_of_birth",
            field=models.DateField(
                blank=True, null=True, verbose_name="დაბადების თარიღი"
            ),
        ),
        migrations.AddField(
            model_name="child",
            name="nickname",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="ნიქნეიმი"
            ),
        ),
        migrations.AddField(
            model_name="child",
            name="sex",
            field=models.CharField(
                blank=True,
                choices=[("male", "ბიჭი"), ("female", "გოგო")],
                null=True,
                verbose_name="სქესი",
            ),
        ),
        migrations.AddField(
            model_name="child",
            name="logo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="user.logo",
                verbose_name="ლოგო",
            ),
        ),
    ]
