# Generated by Django 4.2.3 on 2025-11-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_topic_description_topic_grade"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="image",
            field=models.JSONField(blank=True, null=True, verbose_name="სურათი"),
        ),
        migrations.AddField(
            model_name="topic",
            name="video",
            field=models.JSONField(blank=True, null=True, verbose_name="ზედა ვიდეო"),
        ),
    ]
