# Generated by Django 4.2.3 on 2025-11-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_topic_image_topic_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="topic",
            name="video",
            field=models.JSONField(blank=True, null=True, verbose_name="ვიდეო"),
        ),
    ]
