# Generated by Django 4.2.3 on 2025-11-20 13:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_alter_topic_video"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="topic",
            name="subject",
        ),
        migrations.AddField(
            model_name="subject",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="subject",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="subject",
            name="topic",
            field=models.ManyToManyField(
                blank=True, related_name="subjects", to="core.topic"
            ),
        ),
        migrations.AddField(
            model_name="topic",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="topic",
            name="update_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
