# Generated by Django 4.2.3 on 2025-11-25 12:41

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_remove_topic_subject_subject_is_active_subject_price_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grade",
            name="level",
            field=models.CharField(max_length=50, verbose_name="კლასი"),
        ),
        migrations.AlterField(
            model_name="subject",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="აქტიური"),
        ),
        migrations.AlterField(
            model_name="subject",
            name="name",
            field=models.CharField(max_length=100, verbose_name="საგნის სახელი"),
        ),
        migrations.AlterField(
            model_name="subject",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="ფასი"
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="topic",
            field=models.ManyToManyField(
                blank=True,
                related_name="subjects",
                to="core.topic",
                verbose_name="თემები",
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="created_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="შექმნის თარიღი"
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="აღწერა"),
        ),
        migrations.AlterField(
            model_name="topic",
            name="grade",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="topics",
                to="core.grade",
                verbose_name="კლასი",
            ),
        ),
        migrations.AlterField(
            model_name="topic",
            name="name",
            field=models.CharField(max_length=100, verbose_name="თემის სახელი"),
        ),
        migrations.AlterField(
            model_name="topic",
            name="update_at",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="განახლების თარიღი"
            ),
        ),
    ]
