# Generated by Django 4.2.3 on 2025-11-20 12:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bog_id", models.CharField(max_length=100, unique=True)),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("redirect_url", models.URLField(blank=True, null=True)),
                ("status", models.CharField(default="PENDING", max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "გადახდა",
                "verbose_name_plural": "გადახდები",
                "db_table": "payments_order",
                "ordering": ["-created_at"],
            },
        ),
    ]
