# Generated by Django 4.2.3 on 2025-11-20 13:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0004_alter_topic_video"),
        ("payments", "0002_order_currency_order_total_amount_order_user_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="currency",
        ),
        migrations.AddField(
            model_name="order",
            name="subject",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.subject",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="bog_id",
            field=models.CharField(default="DUMMY_BOG_ID", max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="external_id",
            field=models.CharField(
                default="DUMMY_EXTERNAL_ID", max_length=100, unique=True
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="redirect_url",
            field=models.URLField(default=""),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("end_date", models.DateTimeField()),
                ("active", models.BooleanField(default=True)),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="payments.order"
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.subject"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
