# Generated by Django 4.2.3 on 2025-11-25 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_child_name_alter_child_parent"),
        ("core", "0006_alter_grade_level_alter_subject_is_active_and_more"),
        ("payments", "0005_alter_order_user"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="subscription",
            options={
                "ordering": ["-start_date"],
                "verbose_name": "აბონიმენტი",
                "verbose_name_plural": "აბონიმენტები",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="parent_order_id",
            field=models.CharField(
                blank=True,
                max_length=100,
                null=True,
                verbose_name="მშობელი შეკვეთის ID",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="bog_id",
            field=models.CharField(
                default="DUMMY_BOG_ID", max_length=100, verbose_name="BOG ID"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="შექმნის თარიღი"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="external_id",
            field=models.CharField(
                default="DUMMY_EXTERNAL_ID",
                max_length=100,
                unique=True,
                verbose_name="გარე ID",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="redirect_url",
            field=models.URLField(default="", verbose_name="გადამისამართების URL"),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("SUCCESS", "Success"),
                    ("FAILED", "Failed"),
                ],
                default="PENDING",
                max_length=50,
                verbose_name="სტატუსი",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="subject",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.subject",
                verbose_name="საგანი",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.FloatField(verbose_name="თანხა"),
        ),
        migrations.AlterField(
            model_name="order",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="განახლების თარიღი"),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.parent",
                verbose_name="მომხმარებელი",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="active",
            field=models.BooleanField(default=True, verbose_name="აქტიური"),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="end_date",
            field=models.DateTimeField(verbose_name="დასრულების თარიღი"),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="payments.order",
                verbose_name="გადახდა",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="start_date",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="დაწყების თარიღი"
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="core.subject",
                verbose_name="საგანი",
            ),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="user.parent",
                verbose_name="მომხმარებელი",
            ),
        ),
        migrations.AlterModelTable(
            name="subscription",
            table="payments_subscription",
        ),
    ]
